### ISSUE TITLE
[HM2014811] Camera FC when using Hebrew translation. - already been solved

### ISSUE THREAD

**Issue by MaGinMP** [kkffiirr/MIUI_V6-HEBREW#1]
Camera gives force close on launch. Happens only when switching to Hebrew translation.
Device: Redmi2 (HM2014811) .

Let me know if you need any further information.

Thanks

**Comment by kkffiirr** [comment]
thanks, already solved this.
wait for the next update, or compile using the current files in the git

**Comment by MaGinMP** [comment]
Thanks!
